using Discord;
using Discord.WebSocket;

namespace MerlDiscordBot;

public static class MerlDiscordBot
{
    #region Logging

    private static void Log(string level, object message, string source = nameof(MerlDiscordBot)) =>
        Console.WriteLine($"[{source, -16}:{level, 5}] {message}");

    internal static void LogDebug(object e, string? source = null)
    {
        const string DEBUG = nameof(DEBUG);
        Console.ForegroundColor = ConsoleColor.Gray;
        if (source == null)
            Log(DEBUG, e);
        else
            Log(DEBUG, e, source);
        Console.ResetColor();
    }

    internal static void LogInfo(object e, string? source = null)
    {
        const string INFO = nameof(INFO);
        Console.ResetColor();
        if (source == null)
            Log(INFO, e);
        else
            Log(INFO, e, source);
        Console.ResetColor();
    }

    internal static void LogWarning(object e, string? source = null)
    {
        const string WARN = nameof(WARN);
        Console.ForegroundColor = ConsoleColor.DarkYellow;
        if (source == null)
            Log(WARN, e);
        else
            Log(WARN, e, source);
        Console.ResetColor();
    }

    internal static void LogError(object e, string? source = null)
    {
        const string ERROR = nameof(ERROR);
        Console.ForegroundColor = ConsoleColor.Red;
        if (source == null)
            Log(ERROR, e);
        else
            Log(ERROR, e, source);
        Console.ResetColor();
    }

    internal static void LogFatal(object e, string? source = null)
    {
        const string FATAL = nameof(FATAL);
        Console.ForegroundColor = ConsoleColor.DarkRed;
        if (source == null)
            Log(FATAL, e);
        else
            Log(FATAL, e, source);
        Console.ResetColor();
    }

    #endregion

    const string COMMAND_NAME = "askmerl";

    public static async Task<int> Main()
    {
        const string TOKEN = "TOKEN";
        try
        {
            var token = Environment.GetEnvironmentVariable(
                TOKEN,
                EnvironmentVariableTarget.Process
            );
            if (token == null)
            {
                LogFatal(
                    $"No token specified. Please specify a token in the {TOKEN} environment variable."
                );
                return 1;
            }

            var client = new DiscordSocketClient();
            client.Log += Client_Log;
            client.Ready += Client_Ready;
            client.SlashCommandExecuted += Client_SlashCommandExecuted;

            var tcs = new TaskCompletionSource<int>();
            client.LoggedOut += Client_LoggedOut;

            await client.LoginAsync(TokenType.Bot, token);
            await client.StartAsync();

            Console.CancelKeyPress += Console_CancelKeyPress;

            return await tcs.Task;

            async Task Client_SlashCommandExecuted(SocketSlashCommand ctx)
            {
                switch (ctx.Data.Name)
                {
                    case COMMAND_NAME:
                        await ctx.RespondAsync(
                            embed: new EmbedBuilder()
                            {
                                Author = new EmbedAuthorBuilder()
                                {
                                    Name = "Merl",
                                    IconUrl = client.CurrentUser.GetAvatarUrl(),
                                },
                                Description = "I don't know.",
                                Color = new Color((byte)0xE2, (byte)0x8A, (byte)0xBF),
                                Footer = new EmbedFooterBuilder()
                                {
                                    Text =
                                        "Responses are generated by AI and may include inaccurate information.",
                                },
                                ImageUrl =
                                    "https://raw.githubusercontent.com/baerchen201/MerlDiscordBot/refs/heads/main/Merl.png",
                                ThumbnailUrl =
                                    "https://raw.githubusercontent.com/baerchen201/MerlDiscordBot/refs/heads/main/morl.png",
                                Title = ctx.Data.Options.First().Value.ToString(),
                            }.Build()
                        );
                        break;
                }
            }

            Task Client_Log(LogMessage logMessage)
            {
                var message =
                    logMessage.Exception == null ? logMessage.Message
                    : string.IsNullOrWhiteSpace(logMessage.Message)
                        ? logMessage.Exception.ToString()
                    : $"{logMessage.Message}: {logMessage.Exception}";
                switch (logMessage.Severity)
                {
                    case LogSeverity.Critical:
                        LogFatal(message, logMessage.Source);
                        break;
                    case LogSeverity.Error:
                        LogError(message, logMessage.Source);
                        break;
                    case LogSeverity.Warning:
                        LogWarning(message, logMessage.Source);
                        break;
                    case LogSeverity.Info:
                        LogInfo(message, logMessage.Source);
                        break;
                    case LogSeverity.Verbose:
                    case LogSeverity.Debug:
                        LogDebug(message, logMessage.Source);
                        break;
                    default:
                        throw new ArgumentOutOfRangeException();
                }

                return Task.CompletedTask;
            }

            async Task Client_Ready()
            {
                LogInfo($"Client logged in as {client.CurrentUser.Username}");
                await client.CreateGlobalApplicationCommandAsync(
                    new SlashCommandBuilder
                    {
                        Name = COMMAND_NAME,
                        Description = "Ask the Minecraft AI Agent Merl a question",
                        Options =
                        [
                            new SlashCommandOptionBuilder()
                            {
                                Name = "question",
                                Description = "The question you want to ask",
                                IsRequired = true,
                                Type = ApplicationCommandOptionType.String,
                            },
                        ],
                        ContextTypes =
                        [
                            InteractionContextType.Guild,
                            InteractionContextType.PrivateChannel,
                        ],
                    }.Build()
                );
            }

            Task Client_LoggedOut()
            {
                LogInfo("Client logged out");
                tcs.SetResult(0);
                return Task.CompletedTask;
            }

            void Console_CancelKeyPress(object? sender, ConsoleCancelEventArgs e)
            {
                LogInfo("Requesting logout...");
                client.LogoutAsync().Wait();
                e.Cancel = true;
            }
        }
        catch (Exception e)
        {
            LogFatal(e);
            return 1;
        }
    }
}
